config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'home'     => 'static_pages#home'
  get 'login'    => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete'logout' => 'sessions#destroy'
  resources :users, only: [:show, :edit, :update]
  namespace :suppervisor do
    resources "users"
    resources "courses"
    resources :subjects
    resources :start_subjects
    resources :course_subjects
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :password_not_require
  before_save   :downcase_email

  validates :name,  presence: true, uniqueness: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true, 
  confirmation: true, unless: :password_not_require
  validates :password_confirmation, length: { minimum: 6 }

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
            BCrypt::Engine.cost
            BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def downcase_email
    self.email = email.downcase
  end

  def remember
    self.remember_token = User.new_token
    self.password_not_require = true
    update_attributes :remember_digest, User.digest(remember_token)
    self.password_not_require = false
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    self.password_not_require = true
    update_attributes :remember_digest, nil
    self.password_not_require = false
  end
end

app/controllers/suppervisor/course_subjects_controller.rb
class Suppervisor::CourseSubjectsController < ApplicationController
  def show
    @courses = Course.all
    if params[:commit]
      @course = Course.find params[:course_id]
      @course_subjects = @course.course_subjects
    end
  end

  def update
    @course_subject = CourseSubject.find params[:id]
    if params[:commit]
      CourseSubject.update(@course_subject.id, status_subjects: @course_subject.status_subjects + 1)
      redirect_to suppervisor_course_subject_path
    end
  end 
end

app/controllers/suppervisor/courses_controller.rb
class Suppervisor::CoursesController < ApplicationController
  before_action :suppervisor_user
  def new
    @course = Course.new
    @subjects = Subject.all
  end

  def create
    @course = Course.new course_params
    if @course.save
      redirect_to [:suppervisor,@course]
      flash[:success] = "Create Course Successful"
    else
      render "new"
    end
  end

  def index
    @courses = Course.paginate page: params[:page]
    @enroll = Enroll.new
  end

  def show
    @course = Course.find params[:id]
    @sujects = @course.subjects
  end

  def edit
    @course = Course.find params[:id]
  end

  def update
    @course = Course.new course_params
    if @course.update_attributes course_params
      flash[:success] = "Course updated"
      redirect_to [:suppervisor, @course]
    else
      render "edit"
    end
  end

  def destroy
    @course = Course.find params[:id]
    @course.destroy
    flash[:success] = "Course deleted"
    redirect_to suppervisor_courses_url
  end
  private
  def course_params
    params.require(:course).permit(:name, :instruction, :subject_ids => [])
  end
end

app/controllers/suppervisor/subjects_controller.rb
class Suppervisor::SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def new
    @subject = Subject.new
    4.times {@subject.lessons.build}
  end

  def index
    @subjects = Subject.all.paginate page: params[:page], per_page: 15
  end
  
  def show
    @subject = Subject.find params[:id]
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = "Successfully add new subject!"
      redirect_to suppervisor_subjects_path
    else
      flash.now[:danger] = "Something went wrong!"
      render "new"
    end
  end

  def destroy
    @subject = Subject.find params[:id]
    @subject.destroy
    redirect_to suppervisor_subjects_path
  end

  private

    def set_subject
      @subject = Subject.find params[:id]
    end

    def subject_params
      params.require(:subject).permit(:name, lessons_attributes: [:id, :name, :content])
    end
  
end

app/controllers/suppervisor/users_controller.rb
class Suppervisor::UsersController < ApplicationController
  before_action :correct_user, only: [:edit,:update]
  before_action :logged_in_user, only: [:index,:edit,:update,:destroy]

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "Profile updated"
      redirect_to [:suppervisor,@user]
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless current_user? @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit,:update]
  before_action :logged_in_user, only: [:index,:edit,:update,:destroy]

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "Profile updated"
      redirect_to [:suppervisor,@user]
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless current_user? @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/suppervisor/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:suppervisor,@user]) do |f| %>
      <%= render "shared/error_user", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target=_blank>(change avatar)</a>
    </div>
  </div>
</div>

app/views/suppervisor/users/index.html.erb
<% provide(:title, "All Trainees") %>
<h1>All Trainees</h1>
<% if current_user.is_suppervisor? %>
  <%= link_to "Create New Trainee",new_suppervisor_user_path %>
<%end%>
<table class="table table-condensed" style="width:50%" align = "center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name ,[:suppervisor, user] %></td>
        <td>
          <% if current_user.is_suppervisor? %>
            <%= link_to "Edit", edit_suppervisor_user_path(trainee)%>
            <%= link_to "Delete", suppervisor_user_path(trainee), 
                  method: :delete, data: {confirm: "You sure?"} %>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/suppervisor/users/new.html.erb
<% provide(:title, "New Trainee") %>
<h1>New Trainee</h1>
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:suppervisor, @user]) do |f| %>
      <%= render "shared/error_user" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>