config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'home'     => 'static_pages#home'
  get 'login'    => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete'logout' => 'sessions#destroy'
  resources :users, only: [:show, :edit, :update]
  namespace :suppervisor do
    resources "users"
    resources "courses"
    resources :subjects
    resources :start_subjects
    resources :course_subjects
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :course
  has_many :course_subjects, dependent: :destroy
  has_many :course_subjects
  has_many :lessons, dependent: :destroy
  accepts_nested_attributes_for :lessons, allow_destroy: true
end

app/controllers/suppervisor/course_subjects_controller.rb
class Suppervisor::CourseSubjectsController < ApplicationController
  def show
    @courses = Course.all
    if params[:commit]
      @course = Course.find params[:course_id]
      @course_subjects = @course.course_subjects
    end
  end

  def update
    @course_subject = CourseSubject.find params[:id]
    if params[:commit]
      CourseSubject.update(@course_subject.id, status_subjects: @course_subject.status_subjects + 1)
      redirect_to suppervisor_course_subject_path
    end
  end 
end

app/controllers/suppervisor/courses_controller.rb
class Suppervisor::CoursesController < ApplicationController
  before_action :suppervisor_user
  def new
    @course = Course.new
    @subjects = Subject.all
  end

  def create
    @course = Course.new course_params
    if @course.save
      redirect_to [:suppervisor,@course]
      flash[:success] = "Create Course Successful"
    else
      render "new"
    end
  end

  def index
    @courses = Course.paginate page: params[:page]
    @enroll = Enroll.new
  end

  def show
    @course = Course.find params[:id]
    @sujects = @course.subjects
  end

  def edit
    @course = Course.find params[:id]
  end

  def update
    @course = Course.new course_params
    if @course.update_attributes course_params
      flash[:success] = "Course updated"
      redirect_to [:suppervisor, @course]
    else
      render "edit"
    end
  end

  def destroy
    @course = Course.find params[:id]
    @course.destroy
    flash[:success] = "Course deleted"
    redirect_to suppervisor_courses_url
  end
  private
  def course_params
    params.require(:course).permit(:name, :instruction, :subject_ids => [])
  end
end

app/controllers/suppervisor/subjects_controller.rb
class Suppervisor::SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def new
    @subject = Subject.new
    4.times {@subject.lessons.build}
  end

  def index
    @subjects = Subject.all.paginate page: params[:page], per_page: 15
  end
  
  def show
    @subject = Subject.find params[:id]
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = "Successfully add new subject!"
      redirect_to suppervisor_subjects_path
    else
      flash.now[:danger] = "Something went wrong!"
      render "new"
    end
  end

  def destroy
    @subject = Subject.find params[:id]
    @subject.destroy
    redirect_to suppervisor_subjects_path
  end

  private

    def set_subject
      @subject = Subject.find params[:id]
    end

    def subject_params
      params.require(:subject).permit(:name, lessons_attributes: [:id, :name, :content])
    end
  
end

app/controllers/suppervisor/users_controller.rb
class Suppervisor::UsersController < ApplicationController
  before_action :correct_user, only: [:edit,:update]
  before_action :logged_in_user, only: [:index,:edit,:update,:destroy]

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "Profile updated"
      redirect_to [:suppervisor,@user]
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless current_user? @user
  end
end

app/views/suppervisor/subjects/_form.html.erb
<%= form_for([:suppervisor,@subject]) do |f| %>
  <%= render "shared/error_message", object: f.object %>
  <div class="form-group"><%= f.label :name %>
  <%= f.text_field :name, autofocus: true, class: "form-control" %></div>

  <div class="form-group">
    <p><%= f.fields_for :lessons do |lesson_fields| %>
      <%= render "lesson_fields", f: lesson_fields %>
    <% end %></p>
    <br/><p>
    <%= link_to_add_fields "Add Lessons", f, :lessons %></p>
  </div>

  <div><%= f.submit "Save", class: "btn btn-primary form-control" %></div>
<% end %>

app/views/suppervisor/subjects/_lesson_fields.html.erb
<div class="fields">
  <p>
    <%= f.label :name, "name lesson" %>
    <%= f.text_field :name, :rows => 1, autofocus: true, class: "form-control" %><br />
    <%= f.label :content, "content lesson" %>
    <%= f.text_area :content, :rows => 2, autofocus: true, class: "form-control" %><br />
  </p>
</div>

app/views/suppervisor/subjects/index.html.erb
<% provide :title, "Supervisor | Subjects" %>

<h1 class="page-header">All Subjects</h1>

<% if @subjects.any? %>
  <%= will_paginate @subjects %>
  <table class="table">
    <thead>
      <tr>
      	<th>id</th>
        <th>Name</th>
        <th>Number of lessons</th>
        <th>show</th>
        <th>destroy</th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <th><%= subject.id %></th>
          <th><%= subject.name %></th>
          <th><%= subject.lessons.count %></th>
          <th><%= link_to "Show", suppervisor_subject_path(subject) %></th>
          <th><%= link_to "Delete", suppervisor_subject_path(subject),
          data: { confirm: "Are you sure?", method: :delete } %><th>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info">There is no subject available right now!</div>
<% end %>

<%= link_to "New Subject", new_suppervisor_subject_path, class: "btn btn-primary" %>

app/views/suppervisor/subjects/new.html.erb
<h1>new subjects</h1>
 
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/suppervisor/subjects/show.html.erb
<% provide :title, "Supervisor | Subject's Details" %>

<h1 class="page-header">Subject's Details</h1>

<div class="panel panel-primary">
  <div class="panel-heading"><h3><%= @subject.name %></h3></div>
  <div class="panel-body">
    <h4>Lessons</h4>
    <ul class="list-group">
      <%= render @subject.lessons %>
    </ul>
  </div>
</div>
<p><%= link_to "Back", suppervisor_subjects_path %></p>