config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'home'     => 'static_pages#home'
  get 'login'    => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete'logout' => 'sessions#destroy'
  resources :users, only: [:show, :edit, :update]
  namespace :suppervisor do
    resources "users"
    resources "courses"
    resources :subjects
    resources :start_subjects
    resources :course_subjects
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :users
  has_many :course_subjects, dependent: :destroy
  has_many :subjects, through: :course_subjects
  validates :name,  presence: true, uniqueness: true, length: { maximum: 50 },
        allow_blank: true
  validates :instruction,  presence: true, uniqueness: true, length: { maximum: 500 }, 
        allow_blank: true
  has_many :subjects
end

app/controllers/suppervisor/course_subjects_controller.rb
class Suppervisor::CourseSubjectsController < ApplicationController
  def show
    @courses = Course.all
    if params[:commit]
      @course = Course.find params[:course_id]
      @course_subjects = @course.course_subjects
    end
  end

  def update
    @course_subject = CourseSubject.find params[:id]
    if params[:commit]
      CourseSubject.update(@course_subject.id, status_subjects: @course_subject.status_subjects + 1)
      redirect_to suppervisor_course_subject_path
    end
  end 
end

app/controllers/suppervisor/courses_controller.rb
class Suppervisor::CoursesController < ApplicationController
  before_action :suppervisor_user
  def new
    @course = Course.new
    @subjects = Subject.all
  end

  def create
    @course = Course.new course_params
    if @course.save
      redirect_to [:suppervisor,@course]
      flash[:success] = "Create Course Successful"
    else
      render "new"
    end
  end

  def index
    @courses = Course.paginate page: params[:page]
    @enroll = Enroll.new
  end

  def show
    @course = Course.find params[:id]
    @sujects = @course.subjects
  end

  def edit
    @course = Course.find params[:id]
  end

  def update
    @course = Course.new course_params
    if @course.update_attributes course_params
      flash[:success] = "Course updated"
      redirect_to [:suppervisor, @course]
    else
      render "edit"
    end
  end

  def destroy
    @course = Course.find params[:id]
    @course.destroy
    flash[:success] = "Course deleted"
    redirect_to suppervisor_courses_url
  end
  private
  def course_params
    params.require(:course).permit(:name, :instruction, :subject_ids => [])
  end
end

app/controllers/suppervisor/subjects_controller.rb
class Suppervisor::SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def new
    @subject = Subject.new
    4.times {@subject.lessons.build}
  end

  def index
    @subjects = Subject.all.paginate page: params[:page], per_page: 15
  end
  
  def show
    @subject = Subject.find params[:id]
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = "Successfully add new subject!"
      redirect_to suppervisor_subjects_path
    else
      flash.now[:danger] = "Something went wrong!"
      render "new"
    end
  end

  def destroy
    @subject = Subject.find params[:id]
    @subject.destroy
    redirect_to suppervisor_subjects_path
  end

  private

    def set_subject
      @subject = Subject.find params[:id]
    end

    def subject_params
      params.require(:subject).permit(:name, lessons_attributes: [:id, :name, :content])
    end
  
end

app/controllers/suppervisor/users_controller.rb
class Suppervisor::UsersController < ApplicationController
  before_action :correct_user, only: [:edit,:update]
  before_action :logged_in_user, only: [:index,:edit,:update,:destroy]

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "Profile updated"
      redirect_to [:suppervisor,@user]
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless current_user? @user
  end
end

app/views/suppervisor/courses/edit.html.erb
<% provide(:title, "Edit course") %>
<h1>Edit Course</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:suppervisor,@course]) do |f| %>
      <%= render "shared/error_course" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :instruction %>
      <%= f.text_field :instruction, class: "form-control" %>
      <%= f.submit "Save Chance", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/suppervisor/courses/index.html.erb
<% provide(:title, 'All Courses') %> 
<h1>All Courses</h1>
  <h3><%= link_to "New Course", new_suppervisor_course_path %></h3>
<table class="table table-bordered">
  <thead>
    <tr>
    <th>Course</th>
    <th>Instruction</th>
    <th>Action</th>
    <th>Manage Course</th>
    </tr>
  </thead>
  <tbody>
    <%@courses.each do |course|%>
      <tr>
        <td><%= link_to course.name ,[:suppervisor, course]%></td>
        <td><%= course.instruction %></td>
        <td>
          <% if current_user.is_suppervisor?%>
            <%= link_to "Edit", edit_suppervisor_course_path(course)%>|
            <%= link_to "Delete", suppervisor_course_path(course), method: :delete, data: {confirm: "You sure?"} %>
          <%end%>
        </td>
        <td>
        <%= link_to "Start","#",class: "btn btn-large btn-primary"%>
        <%= link_to "End","#",class: "btn btn-large btn-primary"%>
        </td>   
      </tr>
    <%end%>
  </tbody>
</table>
<%= will_paginate%>

app/views/suppervisor/courses/new.html.erb
<% provide(:title, "Create new course") %>
<h1>Create New Course</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:suppervisor,@course]) do |f| %>
      <%= render "shared/error_course" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :instruction %>
      <%= f.text_field :instruction, class: "form-control" %>
      <div class="span6">
        <%= f.label :subject %>
        <%= f.collection_check_boxes :subject_ids, Subject.all, :id, :name %>
      </div>
      <%= f.submit "Create Course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/suppervisor/courses/show.html.erb
<% provide(:title, @course.name) %>
<h1>Course <%= @course.id %></h1>
<div class="row">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Intruction</th>
            <th>Subjects of Course</th>
            <th>Members of Course</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @course.name%> </td>
            <td><%= @course.instruction %></td>
            <td>
              <% @sujects.each do |suject|%>
                <%= suject.name%><br>
              <%end%>
            </td>
            <td>#</td>
          </tr>
        </tbody>
      </table>
</div>